# This is a basic workflow to help you get started with Actions

name: Deploy to GCloud

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: 'Checkout repository content'
      uses: 'actions/checkout@v2'

    - id: 'auth'
      name: 'Authenticate to GCloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/825841044811/locations/global/workloadIdentityPools/ironman-challenge/providers/ironman-challenge-provider'
        service_account: 'githubdeploy@ironmanchallengetracker.iam.gserviceaccount.com'

    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'app.yaml'
        promote: true
        version: 'v1'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'


# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   deploy:
#     runs-on: ubuntu-lastest
#     steps:
#     - name: Deploy an App Engine app
#       id: deploy-app
#       uses: google-github-actions/deploy-appengine@v0.1.0
#       with:
#         project: ${{ secrets.gcp_project }}
#         deliverables: app.yaml
#         credentials: ${{ secrets.gcp_credentials }}
